export const moradorLegacyFlagMap: Record<string, string> = {
  'ALLOW_LANCAR_GASTO': 'ALLOW_MORADOR_LANCAR_GASTO',
  'ALLOW_GERENCIAR_CARTOES': 'ALLOW_MORADOR_GERENCIAR_CARTOES',
  'ALLOW_GERENCIAR_CONTAS_FIXAS': 'ALLOW_MORADOR_GERENCIAR_CONTAS_FIXAS',
  'ALLOW_REGISTRAR_NETTING': 'ALLOW_MORADOR_REGISTRAR_NETTING',
  'ALLOW_VER_AUDIT_LOGS': 'ALLOW_MORADOR_VER_AUDIT_LOGS'
};

export const DEFAULT_PERMISSIONS = {
  MORADOR: {
    ALLOW_LANCAR_GASTO: true,
    ALLOW_GERENCIAR_CARTOES: true,
    ALLOW_GERENCIAR_CONTAS_FIXAS: true,
    ALLOW_REGISTRAR_NETTING: true,
    ALLOW_VER_AUDIT_LOGS: true,
    ALLOW_ALTERAR_RENDA: true,
    ALLOW_ALTERAR_NOME: true,
    ALLOW_FECHAR_PERIODO: true,
  },
  VISUALIZADOR: {
    ALLOW_LANCAR_GASTO: false,
    ALLOW_GERENCIAR_CARTOES: false,
    ALLOW_GERENCIAR_CONTAS_FIXAS: false,
    ALLOW_REGISTRAR_NETTING: false,
    ALLOW_VER_AUDIT_LOGS: false,
    ALLOW_ALTERAR_RENDA: false,
    ALLOW_ALTERAR_NOME: false,
    ALLOW_FECHAR_PERIODO: false,
  }
};
